# Workflow name displayed in GitHub Actions dashboard
name: Frontend CI/CD Pipeline

# Define when this workflow is triggered; it runs on pull requests to the 'development' branch
on:
  pull_request:
    branches:
      - development  # Triggers the workflow for pull requests targeting the 'development' branch
    paths:
      - "booked_frontend/**"  # Ensures that the workflow only runs when files under 'booked_frontend/' change

# Define the jobs for this workflow
jobs:
  # Job 1: Frontend Testing and Auto-Merge to Development
  frontend:
    # Display name for the job
    name: Run Tests and Auto-Merge to Development
    # Specifies the operating system for the runner (Ubuntu-based runner)
    runs-on: ubuntu-latest

    # Steps to execute in this job
    steps:   
      # Step 1: Checkout code into the runner environment
      - name: Checkout code
        uses: actions/checkout@v2  # This action pulls the latest code into the runner

      # Step 2: Set up Node.js environment with a specified version
      - name: Set up Node.js
        uses: actions/setup-node@v2  # Uses GitHub's setup-node action to specify the Node.js version
        with:
          node-version: '16'  # Define the Node.js version to use

      # Step 3: Install frontend dependencies
      - name: Install dependencies
        run: |
          npm install
        working-directory: ./booked_frontend  # Ensure this step runs in the 'booked_frontend' directory

      # Step 4: Run tests using npm
      - name: Run Tests
        run: |
          npm test -- --watchAll=false
        working-directory: ./booked_frontend  # Run tests in the 'booked_frontend' directory where tests are located # disabling watch mode for CI

  # Job 2: Auto-Merge Feature Branch to Development
  merge-development:
    # Display name for this job
    name: Auto Merge to Development
    # This job only runs if the 'frontend' job succeeds (tests pass)
    needs: frontend
    runs-on: ubuntu-latest  # Use an Ubuntu runner for this job

    # Steps for this job
    steps:
      # Step 1: Checkout the latest code to prepare for the merge
      - name: Checkout code
        uses: actions/checkout@v2  # Action to pull the latest code into the runner

      # Step 2: Set up Git configuration to enable auto-merging by the GitHub Actions bot
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Merge the feature branch into the development branch
      - name: Merge feature to development
        run: |
          git fetch origin
          git checkout development
          git merge origin/feature-branch-name --no-ff -m "Auto-merging feature to development after tests pass"
          git push origin development

  # Job 3: Auto-Merge Development Branch to Main
  merge-main:
    # Display name for this job
    name: Auto Merge to Main
    # This job only runs if the 'merge-development' job succeeds (feature successfully merged to 'development')
    needs: merge-development
    runs-on: ubuntu-latest  # Use an Ubuntu runner for this job

    # Steps for this job
    steps:
      # Step 1: Checkout the latest code to prepare for the merge
      - name: Checkout code
        uses: actions/checkout@v2  # Pull the latest code into the runner

      # Step 2: Configure Git for the GitHub Actions bot to enable auto-merging
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Merge 'development' branch into 'main'
      - name: Merge development to main
        run: |
          git fetch origin
          git checkout main
          git merge origin/development --no-ff -m "Auto-merging development to main after successful deployment"
          git push origin main
